language: swift
osx_image: xcode9.0

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.4.1
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - xcodebuild -project Syft.xcodeproj -scheme Syft clean build test | xcpretty
  - swiftlint
